package app.akam.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Adwaita / GNOME palette. Accent blue (#3584e4) is reserved for controls only;
// surfaces are neutral, and in dark mode cards sit *lighter* than the window.

private val Accent = Color(0xFF3584E4)

val LightScheme = lightColorScheme(
    primary = Accent,
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC5DCF7),
    onPrimaryContainer = Color(0xFF0A2E5C),
    inversePrimary = Color(0xFFA7C8FF),
    secondary = Accent,
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDCE7F8),
    onSecondaryContainer = Color(0xFF0A2E5C),
    tertiary = Color(0xFF8D4B00),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCC3),
    onTertiaryContainer = Color(0xFF2F1500),
    error = Color(0xFFE01B24),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFCE8E8),
    onErrorContainer = Color(0xFF7A0006),
    background = Color(0xFFFAFAFB),
    onBackground = Color(0xFF1E1E1E),
    surface = Color(0xFFFAFAFB),
    onSurface = Color(0xFF1E1E1E),
    surfaceVariant = Color(0xFFE8E8E8),
    onSurfaceVariant = Color(0xFF5E5C64),
    surfaceTint = Accent,
    inverseSurface = Color(0xFF2E2E2E),
    inverseOnSurface = Color(0xFFF2F0F0),
    outline = Color(0xFFC0C0C0),
    outlineVariant = Color(0xFFE2E2E2),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFDEDEDE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F5F6),
    surfaceContainer = Color(0xFFFFFFFF),
    surfaceContainerHigh = Color(0xFFEDEDED),
    surfaceContainerHighest = Color(0xFFE6E6E6),
)

val DarkScheme = darkColorScheme(
    primary = Accent,
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF1A5FB4),
    onPrimaryContainer = Color(0xFFDDE9FB),
    inversePrimary = Color(0xFF1A5FB4),
    secondary = Accent,
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF363636),
    onSecondaryContainer = Color(0xFFDDE9FB),
    tertiary = Color(0xFFFFB77D),
    onTertiary = Color(0xFF4A2800),
    tertiaryContainer = Color(0xFF6E3900),
    onTertiaryContainer = Color(0xFFFFDCC3),
    error = Color(0xFFFF938C),
    onError = Color(0xFF5C0002),
    errorContainer = Color(0xFF4A1512),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF242424),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF242424),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF3A3A3A),
    onSurfaceVariant = Color(0xFFB7B7B7),
    surfaceTint = Accent,
    inverseSurface = Color(0xFFF2F0F0),
    inverseOnSurface = Color(0xFF2E2E2E),
    outline = Color(0xFF5E5E5E),
    outlineVariant = Color(0xFF3D3D3D),
    surfaceBright = Color(0xFF3A3A3A),
    surfaceDim = Color(0xFF242424),
    surfaceContainerLowest = Color(0xFF1E1E1E),
    surfaceContainerLow = Color(0xFF282828),
    surfaceContainer = Color(0xFF303030),
    surfaceContainerHigh = Color(0xFF363636),
    surfaceContainerHighest = Color(0xFF3C3C3C),
)
